In [35]:
import numpy as np

In [36]:
a=np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [37]:
b=np.array([[9.0,6.0,3.0],[5.0,7.0,4.0]])
print(b)

[[9. 6. 3.]
 [5. 7. 4.]]


In [38]:
# get dimensions
a.ndim

1

In [39]:
b.ndim

2

In [40]:
a.shape

(3,)

In [41]:
b.shape

(2, 3)

In [42]:
a.dtype

dtype('int8')

In [43]:
a.itemsize

1

In [44]:
a.nbytes

3

# accessing/changing specific elements,row,columns

In [45]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
#get a specific element
a[0,5]

6

In [47]:
a[0,-3]

5

In [48]:
#get row only
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
#get column only
a[:,3]

array([ 4, 11])

In [50]:
#[startindex:endindex:stepsize]
a[0,2:-1:1]

array([3, 4, 5, 6])

In [51]:
#3d array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
a[1,0,1]

6

In [53]:
a[:,1,:]

array([[3, 4],
       [7, 8]])

# initilizing different types of arrays

## all zeros
np.zeros(2,2)

In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [60]:
np.full((2,2),99, dtype=float)

array([[99., 99.],
       [99., 99.]])

In [65]:
np.full_like(a,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [66]:
np.random.rand(4,2)

array([[0.31229693, 0.06882753],
       [0.11038974, 0.16200064],
       [0.75577967, 0.89831417],
       [0.78350509, 0.71525743]])

In [68]:
np.random.random_sample(a.shape)

array([[[0.47009442, 0.18087331],
        [0.00967316, 0.82803441]],

       [[0.36875894, 0.5677564 ],
        [0.13064586, 0.86050571]]])

In [71]:
np.random.randint(10,50, size=(3,3))

array([[16, 10, 30],
       [40, 12, 16],
       [44, 14, 46]])

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output =np.ones((5,5))
print(output)
z= np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
a=np.array([1,2,3])
b=a.copy()
a[0]=100
b[0]=200
print(a)
print(b)

[100   2   3]
[200   2   3]


# mathematics with numpy

In [91]:
a=np.array([1,2,3])


In [92]:
a+2

array([3, 4, 5])

In [93]:
a-2

array([-1,  0,  1])

In [94]:
a*2

array([2, 4, 6])

In [95]:
a/2

array([0, 1, 1])

In [96]:
a**2

array([1, 4, 9])

In [97]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# statistics

In [100]:
a=np.array([[4,3,5],[7,6,4]])

In [103]:
np.min(a,axis=0)

array([4, 3, 4])

In [105]:
np.max(a,axis=0)

array([7, 6, 5])

In [106]:
np.sum(a)

29

In [107]:
np.sum(a,axis=0)

array([11,  9,  9])

In [108]:
np.sum(a,axis=1)

array([12, 17])

# Reorganizing Arrays

In [110]:
before=np.array([[4,3,5,9],[7,6,4,8]])
before

array([[4, 3, 5, 9],
       [7, 6, 4, 8]])

In [113]:
after=before.reshape((4,2))
after

array([[4, 3],
       [5, 9],
       [7, 6],
       [4, 8]])

In [114]:
# vertically stacking vectors
v1=np.array([4,3,5,9])
v2=np.array([7,6,4,8])
np.vstack([v1,v2])


array([[4, 3, 5, 9],
       [7, 6, 4, 8]])

In [115]:
np.hstack([v1,v2])

array([4, 3, 5, 9, 7, 6, 4, 8])

# miscellaneous

In [119]:
filedata=np.genfromtxt('pokemon_data.txt', delimiter='')

ValueError: Some errors were detected !
    Line #2 (got 12 columns instead of 16)
    Line #3 (got 12 columns instead of 16)
    Line #4 (got 12 columns instead of 16)
    Line #5 (got 13 columns instead of 16)
    Line #6 (got 11 columns instead of 16)
    Line #7 (got 11 columns instead of 16)
    Line #8 (got 12 columns instead of 16)
    Line #9 (got 14 columns instead of 16)
    Line #10 (got 14 columns instead of 16)
    Line #11 (got 11 columns instead of 16)
    Line #12 (got 11 columns instead of 16)
    Line #13 (got 11 columns instead of 16)
    Line #14 (got 12 columns instead of 16)
    Line #15 (got 11 columns instead of 16)
    Line #16 (got 11 columns instead of 16)
    Line #17 (got 12 columns instead of 16)
    Line #18 (got 12 columns instead of 16)
    Line #19 (got 12 columns instead of 16)
    Line #20 (got 12 columns instead of 16)
    Line #21 (got 13 columns instead of 16)
    Line #22 (got 12 columns instead of 16)
    Line #23 (got 12 columns instead of 16)
    Line #24 (got 12 columns instead of 16)
    Line #25 (got 13 columns instead of 16)
    Line #26 (got 11 columns instead of 16)
    Line #27 (got 11 columns instead of 16)
    Line #28 (got 12 columns instead of 16)
    Line #29 (got 12 columns instead of 16)
    Line #30 (got 11 columns instead of 16)
    Line #31 (got 11 columns instead of 16)
    Line #32 (got 11 columns instead of 16)
    Line #33 (got 11 columns instead of 16)
    Line #34 (got 11 columns instead of 16)
    Line #35 (got 11 columns instead of 16)
    Line #36 (got 12 columns instead of 16)
    Line #37 (got 11 columns instead of 16)
    Line #38 (got 12 columns instead of 16)
    Line #39 (got 12 columns instead of 16)
    Line #40 (got 11 columns instead of 16)
    Line #41 (got 12 columns instead of 16)
    Line #42 (got 11 columns instead of 16)
    Line #43 (got 11 columns instead of 16)
    Line #44 (got 11 columns instead of 16)
    Line #45 (got 11 columns instead of 16)
    Line #46 (got 12 columns instead of 16)
    Line #47 (got 12 columns instead of 16)
    Line #48 (got 12 columns instead of 16)
    Line #49 (got 12 columns instead of 16)
    Line #50 (got 12 columns instead of 16)
    Line #51 (got 12 columns instead of 16)
    Line #52 (got 12 columns instead of 16)
    Line #53 (got 12 columns instead of 16)
    Line #54 (got 12 columns instead of 16)
    Line #55 (got 12 columns instead of 16)
    Line #56 (got 12 columns instead of 16)
    Line #57 (got 11 columns instead of 16)
    Line #58 (got 11 columns instead of 16)
    Line #59 (got 11 columns instead of 16)
    Line #60 (got 11 columns instead of 16)
    Line #61 (got 11 columns instead of 16)
    Line #62 (got 11 columns instead of 16)
    Line #63 (got 11 columns instead of 16)
    Line #64 (got 11 columns instead of 16)
    Line #65 (got 11 columns instead of 16)
    Line #66 (got 11 columns instead of 16)
    Line #67 (got 11 columns instead of 16)
    Line #68 (got 11 columns instead of 16)
    Line #69 (got 12 columns instead of 16)
    Line #70 (got 11 columns instead of 16)
    Line #71 (got 11 columns instead of 16)
    Line #72 (got 11 columns instead of 16)
    Line #73 (got 12 columns instead of 16)
    Line #74 (got 11 columns instead of 16)
    Line #75 (got 11 columns instead of 16)
    Line #76 (got 11 columns instead of 16)
    Line #77 (got 12 columns instead of 16)
    Line #78 (got 12 columns instead of 16)
    Line #79 (got 12 columns instead of 16)
    Line #80 (got 12 columns instead of 16)
    Line #81 (got 12 columns instead of 16)
    Line #82 (got 12 columns instead of 16)
    Line #83 (got 12 columns instead of 16)
    Line #84 (got 12 columns instead of 16)
    Line #85 (got 11 columns instead of 16)
    Line #86 (got 11 columns instead of 16)
    Line #87 (got 12 columns instead of 16)
    Line #88 (got 12 columns instead of 16)
    Line #89 (got 13 columns instead of 16)
    Line #90 (got 12 columns instead of 16)
    Line #91 (got 12 columns instead of 16)
    Line #92 (got 12 columns instead of 16)
    Line #93 (got 12 columns instead of 16)
    Line #94 (got 12 columns instead of 16)
    Line #95 (got 11 columns instead of 16)
    Line #96 (got 12 columns instead of 16)
    Line #97 (got 11 columns instead of 16)
    Line #98 (got 11 columns instead of 16)
    Line #99 (got 11 columns instead of 16)
    Line #100 (got 12 columns instead of 16)
    Line #101 (got 12 columns instead of 16)
    Line #102 (got 12 columns instead of 16)
    Line #103 (got 12 columns instead of 16)
    Line #104 (got 13 columns instead of 16)
    Line #105 (got 12 columns instead of 16)
    Line #106 (got 11 columns instead of 16)
    Line #107 (got 11 columns instead of 16)
    Line #108 (got 11 columns instead of 16)
    Line #109 (got 11 columns instead of 16)
    Line #110 (got 11 columns instead of 16)
    Line #111 (got 11 columns instead of 16)
    Line #112 (got 12 columns instead of 16)
    Line #113 (got 12 columns instead of 16)
    Line #114 (got 11 columns instead of 16)
    Line #115 (got 11 columns instead of 16)
    Line #116 (got 11 columns instead of 16)
    Line #117 (got 11 columns instead of 16)
    Line #118 (got 11 columns instead of 16)
    Line #119 (got 11 columns instead of 16)
    Line #120 (got 11 columns instead of 16)
    Line #121 (got 12 columns instead of 16)
    Line #122 (got 12 columns instead of 16)
    Line #123 (got 11 columns instead of 16)
    Line #124 (got 11 columns instead of 16)
    Line #125 (got 11 columns instead of 16)
    Line #126 (got 12 columns instead of 16)
    Line #127 (got 11 columns instead of 16)
    Line #128 (got 11 columns instead of 16)
    Line #129 (got 11 columns instead of 16)
    Line #130 (got 11 columns instead of 16)
    Line #131 (got 11 columns instead of 16)
    Line #132 (got 12 columns instead of 16)
    Line #133 (got 13 columns instead of 16)
    Line #134 (got 12 columns instead of 16)
    Line #135 (got 12 columns instead of 16)
    Line #136 (got 11 columns instead of 16)
    Line #137 (got 11 columns instead of 16)
    Line #138 (got 11 columns instead of 16)
    Line #139 (got 13 columns instead of 16)
    Line #140 (got 11 columns instead of 16)
    Line #141 (got 11 columns instead of 16)
    Line #142 (got 12 columns instead of 16)
    Line #143 (got 13 columns instead of 16)
    Line #144 (got 12 columns instead of 16)
    Line #145 (got 11 columns instead of 16)
    Line #146 (got 11 columns instead of 16)
    Line #147 (got 11 columns instead of 16)
    Line #148 (got 11 columns instead of 16)
    Line #149 (got 11 columns instead of 16)
    Line #150 (got 11 columns instead of 16)
    Line #151 (got 12 columns instead of 16)
    Line #152 (got 12 columns instead of 16)
    Line #153 (got 12 columns instead of 16)
    Line #154 (got 12 columns instead of 16)
    Line #155 (got 12 columns instead of 16)
    Line #156 (got 13 columns instead of 16)
    Line #157 (got 11 columns instead of 16)
    Line #158 (got 12 columns instead of 16)
    Line #159 (got 12 columns instead of 16)
    Line #160 (got 12 columns instead of 16)
    Line #161 (got 11 columns instead of 16)
    Line #162 (got 11 columns instead of 16)
    Line #163 (got 12 columns instead of 16)
    Line #164 (got 11 columns instead of 16)
    Line #165 (got 14 columns instead of 16)
    Line #166 (got 13 columns instead of 16)
    Line #167 (got 11 columns instead of 16)
    Line #168 (got 11 columns instead of 16)
    Line #169 (got 11 columns instead of 16)
    Line #170 (got 11 columns instead of 16)
    Line #171 (got 11 columns instead of 16)
    Line #172 (got 11 columns instead of 16)
    Line #173 (got 11 columns instead of 16)
    Line #174 (got 11 columns instead of 16)
    Line #175 (got 11 columns instead of 16)
    Line #176 (got 11 columns instead of 16)
    Line #177 (got 11 columns instead of 16)
    Line #178 (got 11 columns instead of 16)
    Line #179 (got 12 columns instead of 16)
    Line #180 (got 12 columns instead of 16)
    Line #181 (got 12 columns instead of 16)
    Line #182 (got 12 columns instead of 16)
    Line #183 (got 12 columns instead of 16)
    Line #184 (got 12 columns instead of 16)
    Line #185 (got 12 columns instead of 16)
    Line #186 (got 12 columns instead of 16)
    Line #187 (got 12 columns instead of 16)
    Line #188 (got 11 columns instead of 16)
    Line #189 (got 11 columns instead of 16)
    Line #190 (got 12 columns instead of 16)
    Line #191 (got 11 columns instead of 16)
    Line #192 (got 12 columns instead of 16)
    Line #193 (got 12 columns instead of 16)
    Line #194 (got 12 columns instead of 16)
    Line #195 (got 11 columns instead of 16)
    Line #196 (got 11 columns instead of 16)
    Line #197 (got 11 columns instead of 16)
    Line #198 (got 13 columns instead of 16)
    Line #199 (got 11 columns instead of 16)
    Line #200 (got 12 columns instead of 16)
    Line #201 (got 12 columns instead of 16)
    Line #202 (got 11 columns instead of 16)
    Line #203 (got 11 columns instead of 16)
    Line #204 (got 12 columns instead of 16)
    Line #205 (got 12 columns instead of 16)
    Line #206 (got 12 columns instead of 16)
    Line #207 (got 11 columns instead of 16)
    Line #208 (got 11 columns instead of 16)
    Line #209 (got 11 columns instead of 16)
    Line #210 (got 12 columns instead of 16)
    Line #211 (got 12 columns instead of 16)
    Line #212 (got 12 columns instead of 16)
    Line #213 (got 11 columns instead of 16)
    Line #214 (got 11 columns instead of 16)
    Line #215 (got 12 columns instead of 16)
    Line #216 (got 12 columns instead of 16)
    Line #217 (got 11 columns instead of 16)
    Line #218 (got 11 columns instead of 16)
    Line #219 (got 11 columns instead of 16)
    Line #220 (got 12 columns instead of 16)
    Line #221 (got 11 columns instead of 16)
    Line #222 (got 12 columns instead of 16)
    Line #223 (got 11 columns instead of 16)
    Line #224 (got 12 columns instead of 16)
    Line #225 (got 12 columns instead of 16)
    Line #226 (got 13 columns instead of 16)
    Line #227 (got 11 columns instead of 16)
    Line #228 (got 11 columns instead of 16)
    Line #229 (got 12 columns instead of 16)
    Line #230 (got 12 columns instead of 16)
    Line #231 (got 13 columns instead of 16)
    Line #232 (got 12 columns instead of 16)
    Line #233 (got 12 columns instead of 16)
    Line #234 (got 13 columns instead of 16)
    Line #235 (got 12 columns instead of 16)
    Line #236 (got 11 columns instead of 16)
    Line #237 (got 11 columns instead of 16)
    Line #238 (got 11 columns instead of 16)
    Line #239 (got 12 columns instead of 16)
    Line #240 (got 12 columns instead of 16)
    Line #241 (got 12 columns instead of 16)
    Line #242 (got 12 columns instead of 16)
    Line #243 (got 11 columns instead of 16)
    Line #244 (got 11 columns instead of 16)
    Line #245 (got 12 columns instead of 16)
    Line #246 (got 12 columns instead of 16)
    Line #247 (got 12 columns instead of 16)
    Line #248 (got 12 columns instead of 16)
    Line #249 (got 12 columns instead of 16)
    Line #250 (got 13 columns instead of 16)
    Line #251 (got 12 columns instead of 16)
    Line #252 (got 11 columns instead of 16)
    Line #253 (got 11 columns instead of 16)
    Line #254 (got 11 columns instead of 16)
    Line #255 (got 11 columns instead of 16)
    Line #256 (got 11 columns instead of 16)
    Line #257 (got 11 columns instead of 16)
    Line #258 (got 11 columns instead of 16)
    Line #259 (got 12 columns instead of 16)
    Line #260 (got 11 columns instead of 16)
    Line #261 (got 11 columns instead of 16)
    Line #262 (got 11 columns instead of 16)
    Line #263 (got 11 columns instead of 16)
    Line #264 (got 11 columns instead of 16)
    Line #265 (got 11 columns instead of 16)
    Line #266 (got 11 columns instead of 16)
    Line #267 (got 12 columns instead of 16)
    Line #268 (got 12 columns instead of 16)
    Line #269 (got 12 columns instead of 16)
    Line #270 (got 13 columns instead of 16)
    Line #271 (got 12 columns instead of 16)
    Line #272 (got 12 columns instead of 16)
    Line #273 (got 12 columns instead of 16)
    Line #274 (got 11 columns instead of 16)
    Line #275 (got 11 columns instead of 16)
    Line #276 (got 11 columns instead of 16)
    Line #277 (got 13 columns instead of 16)
    Line #278 (got 11 columns instead of 16)
    Line #279 (got 12 columns instead of 16)
    Line #280 (got 12 columns instead of 16)
    Line #281 (got 13 columns instead of 16)
    Line #282 (got 11 columns instead of 16)
    Line #283 (got 12 columns instead of 16)
    Line #284 (got 12 columns instead of 16)
    Line #285 (got 13 columns instead of 16)
    Line #286 (got 11 columns instead of 16)
    Line #287 (got 11 columns instead of 16)
    Line #288 (got 11 columns instead of 16)
    Line #289 (got 11 columns instead of 16)
    Line #290 (got 11 columns instead of 16)
    Line #291 (got 11 columns instead of 16)
    Line #292 (got 12 columns instead of 16)
    Line #293 (got 11 columns instead of 16)
    Line #294 (got 12 columns instead of 16)
    Line #295 (got 12 columns instead of 16)
    Line #296 (got 12 columns instead of 16)
    Line #297 (got 12 columns instead of 16)
    Line #298 (got 11 columns instead of 16)
    Line #299 (got 12 columns instead of 16)
    Line #300 (got 12 columns instead of 16)
    Line #301 (got 12 columns instead of 16)
    Line #302 (got 12 columns instead of 16)
    Line #303 (got 12 columns instead of 16)
    Line #304 (got 12 columns instead of 16)
    Line #305 (got 12 columns instead of 16)
    Line #306 (got 12 columns instead of 16)
    Line #307 (got 12 columns instead of 16)
    Line #308 (got 13 columns instead of 16)
    Line #309 (got 12 columns instead of 16)
    Line #310 (got 12 columns instead of 16)
    Line #311 (got 11 columns instead of 16)
    Line #312 (got 12 columns instead of 16)
    Line #313 (got 11 columns instead of 16)
    Line #314 (got 11 columns instead of 16)
    Line #315 (got 11 columns instead of 16)
    Line #316 (got 12 columns instead of 16)
    Line #317 (got 12 columns instead of 16)
    Line #318 (got 12 columns instead of 16)
    Line #319 (got 11 columns instead of 16)
    Line #320 (got 11 columns instead of 16)
    Line #321 (got 11 columns instead of 16)
    Line #322 (got 11 columns instead of 16)
    Line #323 (got 11 columns instead of 16)
    Line #324 (got 12 columns instead of 16)
    Line #325 (got 11 columns instead of 16)
    Line #326 (got 11 columns instead of 16)
    Line #327 (got 11 columns instead of 16)
    Line #328 (got 12 columns instead of 16)
    Line #329 (got 13 columns instead of 16)
    Line #330 (got 12 columns instead of 16)
    Line #331 (got 13 columns instead of 16)
    Line #332 (got 12 columns instead of 16)
    Line #333 (got 12 columns instead of 16)
    Line #334 (got 12 columns instead of 16)
    Line #335 (got 12 columns instead of 16)
    Line #336 (got 12 columns instead of 16)
    Line #337 (got 12 columns instead of 16)
    Line #338 (got 13 columns instead of 16)
    Line #339 (got 11 columns instead of 16)
    Line #340 (got 11 columns instead of 16)
    Line #341 (got 12 columns instead of 16)
    Line #342 (got 11 columns instead of 16)
    Line #343 (got 11 columns instead of 16)
    Line #344 (got 11 columns instead of 16)
    Line #345 (got 11 columns instead of 16)
    Line #346 (got 12 columns instead of 16)
    Line #347 (got 11 columns instead of 16)
    Line #348 (got 11 columns instead of 16)
    Line #349 (got 12 columns instead of 16)
    Line #350 (got 12 columns instead of 16)
    Line #351 (got 13 columns instead of 16)
    Line #352 (got 11 columns instead of 16)
    Line #353 (got 11 columns instead of 16)
    Line #354 (got 12 columns instead of 16)
    Line #355 (got 12 columns instead of 16)
    Line #356 (got 13 columns instead of 16)
    Line #357 (got 11 columns instead of 16)
    Line #358 (got 11 columns instead of 16)
    Line #359 (got 11 columns instead of 16)
    Line #360 (got 11 columns instead of 16)
    Line #361 (got 11 columns instead of 16)
    Line #362 (got 12 columns instead of 16)
    Line #363 (got 12 columns instead of 16)
    Line #364 (got 11 columns instead of 16)
    Line #365 (got 12 columns instead of 16)
    Line #366 (got 12 columns instead of 16)
    Line #367 (got 12 columns instead of 16)
    Line #368 (got 13 columns instead of 16)
    Line #369 (got 11 columns instead of 16)
    Line #370 (got 11 columns instead of 16)
    Line #371 (got 12 columns instead of 16)
    Line #372 (got 12 columns instead of 16)
    Line #373 (got 12 columns instead of 16)
    Line #374 (got 12 columns instead of 16)
    Line #375 (got 11 columns instead of 16)
    Line #376 (got 12 columns instead of 16)
    Line #377 (got 12 columns instead of 16)
    Line #378 (got 12 columns instead of 16)
    Line #379 (got 12 columns instead of 16)
    Line #380 (got 12 columns instead of 16)
    Line #381 (got 12 columns instead of 16)
    Line #382 (got 12 columns instead of 16)
    Line #383 (got 11 columns instead of 16)
    Line #384 (got 11 columns instead of 16)
    Line #385 (got 11 columns instead of 16)
    Line #386 (got 11 columns instead of 16)
    Line #387 (got 11 columns instead of 16)
    Line #388 (got 11 columns instead of 16)
    Line #389 (got 12 columns instead of 16)
    Line #390 (got 11 columns instead of 16)
    Line #391 (got 11 columns instead of 16)
    Line #392 (got 12 columns instead of 16)
    Line #393 (got 11 columns instead of 16)
    Line #394 (got 11 columns instead of 16)
    Line #395 (got 12 columns instead of 16)
    Line #396 (got 11 columns instead of 16)
    Line #397 (got 11 columns instead of 16)
    Line #398 (got 11 columns instead of 16)
    Line #399 (got 12 columns instead of 16)
    Line #400 (got 12 columns instead of 16)
    Line #401 (got 12 columns instead of 16)
    Line #402 (got 12 columns instead of 16)
    Line #403 (got 11 columns instead of 16)
    Line #404 (got 11 columns instead of 16)
    Line #405 (got 11 columns instead of 16)
    Line #406 (got 12 columns instead of 16)
    Line #407 (got 11 columns instead of 16)
    Line #408 (got 11 columns instead of 16)
    Line #409 (got 11 columns instead of 16)
    Line #410 (got 12 columns instead of 16)
    Line #411 (got 13 columns instead of 16)
    Line #412 (got 12 columns instead of 16)
    Line #413 (got 12 columns instead of 16)
    Line #414 (got 12 columns instead of 16)
    Line #415 (got 13 columns instead of 16)
    Line #416 (got 11 columns instead of 16)
    Line #417 (got 11 columns instead of 16)
    Line #418 (got 11 columns instead of 16)
    Line #419 (got 12 columns instead of 16)
    Line #420 (got 13 columns instead of 16)
    Line #421 (got 12 columns instead of 16)
    Line #422 (got 13 columns instead of 16)
    Line #423 (got 11 columns instead of 16)
    Line #424 (got 12 columns instead of 16)
    Line #425 (got 11 columns instead of 16)
    Line #426 (got 13 columns instead of 16)
    Line #427 (got 12 columns instead of 16)
    Line #428 (got 13 columns instead of 16)
    Line #429 (got 12 columns instead of 16)
    Line #430 (got 12 columns instead of 16)
    Line #431 (got 12 columns instead of 16)
    Line #432 (got 12 columns instead of 16)
    Line #433 (got 12 columns instead of 16)
    Line #434 (got 11 columns instead of 16)
    Line #435 (got 11 columns instead of 16)
    Line #436 (got 12 columns instead of 16)
    Line #437 (got 11 columns instead of 16)
    Line #438 (got 12 columns instead of 16)
    Line #439 (got 12 columns instead of 16)
    Line #440 (got 11 columns instead of 16)
    Line #441 (got 11 columns instead of 16)
    Line #442 (got 12 columns instead of 16)
    Line #443 (got 12 columns instead of 16)
    Line #444 (got 12 columns instead of 16)
    Line #445 (got 12 columns instead of 16)
    Line #446 (got 11 columns instead of 16)
    Line #447 (got 12 columns instead of 16)
    Line #448 (got 11 columns instead of 16)
    Line #449 (got 11 columns instead of 16)
    Line #450 (got 11 columns instead of 16)
    Line #451 (got 11 columns instead of 16)
    Line #452 (got 11 columns instead of 16)
    Line #453 (got 12 columns instead of 16)
    Line #454 (got 12 columns instead of 16)
    Line #455 (got 11 columns instead of 16)
    Line #456 (got 11 columns instead of 16)
    Line #457 (got 12 columns instead of 16)
    Line #458 (got 12 columns instead of 16)
    Line #459 (got 11 columns instead of 16)
    Line #460 (got 13 columns instead of 16)
    Line #461 (got 13 columns instead of 16)
    Line #462 (got 13 columns instead of 16)
    Line #463 (got 12 columns instead of 16)
    Line #464 (got 12 columns instead of 16)
    Line #465 (got 12 columns instead of 16)
    Line #466 (got 11 columns instead of 16)
    Line #467 (got 11 columns instead of 16)
    Line #468 (got 11 columns instead of 16)
    Line #469 (got 11 columns instead of 16)
    Line #470 (got 11 columns instead of 16)
    Line #471 (got 11 columns instead of 16)
    Line #472 (got 12 columns instead of 16)
    Line #473 (got 11 columns instead of 16)
    Line #474 (got 12 columns instead of 16)
    Line #475 (got 12 columns instead of 16)
    Line #476 (got 11 columns instead of 16)
    Line #477 (got 11 columns instead of 16)
    Line #478 (got 13 columns instead of 16)
    Line #479 (got 11 columns instead of 16)
    Line #480 (got 12 columns instead of 16)
    Line #481 (got 11 columns instead of 16)
    Line #482 (got 11 columns instead of 16)
    Line #483 (got 11 columns instead of 16)
    Line #484 (got 12 columns instead of 16)
    Line #485 (got 12 columns instead of 16)
    Line #486 (got 12 columns instead of 16)
    Line #487 (got 12 columns instead of 16)
    Line #488 (got 11 columns instead of 16)
    Line #489 (got 13 columns instead of 16)
    Line #490 (got 11 columns instead of 16)
    Line #491 (got 12 columns instead of 16)
    Line #492 (got 12 columns instead of 16)
    Line #493 (got 12 columns instead of 16)
    Line #494 (got 12 columns instead of 16)
    Line #495 (got 12 columns instead of 16)
    Line #496 (got 13 columns instead of 16)
    Line #497 (got 11 columns instead of 16)
    Line #498 (got 11 columns instead of 16)
    Line #499 (got 12 columns instead of 16)
    Line #500 (got 13 columns instead of 16)
    Line #501 (got 11 columns instead of 16)
    Line #502 (got 11 columns instead of 16)
    Line #503 (got 12 columns instead of 16)
    Line #504 (got 12 columns instead of 16)
    Line #505 (got 12 columns instead of 16)
    Line #506 (got 12 columns instead of 16)
    Line #507 (got 11 columns instead of 16)
    Line #508 (got 11 columns instead of 16)
    Line #509 (got 11 columns instead of 16)
    Line #510 (got 12 columns instead of 16)
    Line #511 (got 12 columns instead of 16)
    Line #512 (got 12 columns instead of 16)
    Line #513 (got 13 columns instead of 16)
    Line #514 (got 12 columns instead of 16)
    Line #515 (got 12 columns instead of 16)
    Line #516 (got 11 columns instead of 16)
    Line #517 (got 12 columns instead of 16)
    Line #518 (got 11 columns instead of 16)
    Line #519 (got 11 columns instead of 16)
    Line #520 (got 11 columns instead of 16)
    Line #521 (got 12 columns instead of 16)
    Line #522 (got 12 columns instead of 16)
    Line #523 (got 11 columns instead of 16)
    Line #524 (got 11 columns instead of 16)
    Line #525 (got 12 columns instead of 16)
    Line #526 (got 12 columns instead of 16)
    Line #527 (got 11 columns instead of 16)
    Line #528 (got 12 columns instead of 16)
    Line #529 (got 13 columns instead of 16)
    Line #530 (got 12 columns instead of 16)
    Line #531 (got 11 columns instead of 16)
    Line #532 (got 12 columns instead of 16)
    Line #533 (got 12 columns instead of 16)
    Line #534 (got 13 columns instead of 16)
    Line #535 (got 13 columns instead of 16)
    Line #536 (got 13 columns instead of 16)
    Line #537 (got 13 columns instead of 16)
    Line #538 (got 13 columns instead of 16)
    Line #539 (got 11 columns instead of 16)
    Line #540 (got 11 columns instead of 16)
    Line #541 (got 11 columns instead of 16)
    Line #542 (got 12 columns instead of 16)
    Line #543 (got 12 columns instead of 16)
    Line #544 (got 12 columns instead of 16)
    Line #545 (got 11 columns instead of 16)
    Line #546 (got 13 columns instead of 16)
    Line #547 (got 13 columns instead of 16)
    Line #548 (got 11 columns instead of 16)
    Line #549 (got 11 columns instead of 16)
    Line #550 (got 11 columns instead of 16)
    Line #551 (got 11 columns instead of 16)
    Line #552 (got 12 columns instead of 16)
    Line #553 (got 13 columns instead of 16)
    Line #554 (got 11 columns instead of 16)
    Line #555 (got 12 columns instead of 16)
    Line #556 (got 11 columns instead of 16)
    Line #557 (got 11 columns instead of 16)
    Line #558 (got 11 columns instead of 16)
    Line #559 (got 11 columns instead of 16)
    Line #560 (got 12 columns instead of 16)
    Line #561 (got 12 columns instead of 16)
    Line #562 (got 11 columns instead of 16)
    Line #563 (got 11 columns instead of 16)
    Line #564 (got 11 columns instead of 16)
    Line #565 (got 11 columns instead of 16)
    Line #566 (got 11 columns instead of 16)
    Line #567 (got 11 columns instead of 16)
    Line #568 (got 11 columns instead of 16)
    Line #569 (got 11 columns instead of 16)
    Line #570 (got 11 columns instead of 16)
    Line #571 (got 11 columns instead of 16)
    Line #572 (got 11 columns instead of 16)
    Line #573 (got 11 columns instead of 16)
    Line #574 (got 11 columns instead of 16)
    Line #575 (got 11 columns instead of 16)
    Line #576 (got 11 columns instead of 16)
    Line #577 (got 11 columns instead of 16)
    Line #578 (got 11 columns instead of 16)
    Line #579 (got 11 columns instead of 16)
    Line #580 (got 12 columns instead of 16)
    Line #581 (got 12 columns instead of 16)
    Line #582 (got 12 columns instead of 16)
    Line #583 (got 11 columns instead of 16)
    Line #584 (got 11 columns instead of 16)
    Line #585 (got 11 columns instead of 16)
    Line #586 (got 11 columns instead of 16)
    Line #587 (got 11 columns instead of 16)
    Line #588 (got 12 columns instead of 16)
    Line #589 (got 12 columns instead of 16)
    Line #590 (got 11 columns instead of 16)
    Line #591 (got 12 columns instead of 16)
    Line #592 (got 11 columns instead of 16)
    Line #593 (got 13 columns instead of 16)
    Line #594 (got 11 columns instead of 16)
    Line #595 (got 11 columns instead of 16)
    Line #596 (got 11 columns instead of 16)
    Line #597 (got 11 columns instead of 16)
    Line #598 (got 12 columns instead of 16)
    Line #599 (got 12 columns instead of 16)
    Line #600 (got 11 columns instead of 16)
    Line #601 (got 11 columns instead of 16)
    Line #602 (got 12 columns instead of 16)
    Line #603 (got 12 columns instead of 16)
    Line #604 (got 12 columns instead of 16)
    Line #605 (got 12 columns instead of 16)
    Line #606 (got 12 columns instead of 16)
    Line #607 (got 12 columns instead of 16)
    Line #608 (got 12 columns instead of 16)
    Line #609 (got 12 columns instead of 16)
    Line #610 (got 11 columns instead of 16)
    Line #611 (got 11 columns instead of 16)
    Line #612 (got 11 columns instead of 16)
    Line #613 (got 12 columns instead of 16)
    Line #614 (got 12 columns instead of 16)
    Line #615 (got 12 columns instead of 16)
    Line #616 (got 11 columns instead of 16)
    Line #617 (got 12 columns instead of 16)
    Line #618 (got 13 columns instead of 16)
    Line #619 (got 11 columns instead of 16)
    Line #620 (got 12 columns instead of 16)
    Line #621 (got 12 columns instead of 16)
    Line #622 (got 12 columns instead of 16)
    Line #623 (got 12 columns instead of 16)
    Line #624 (got 12 columns instead of 16)
    Line #625 (got 11 columns instead of 16)
    Line #626 (got 11 columns instead of 16)
    Line #627 (got 12 columns instead of 16)
    Line #628 (got 12 columns instead of 16)
    Line #629 (got 12 columns instead of 16)
    Line #630 (got 12 columns instead of 16)
    Line #631 (got 11 columns instead of 16)
    Line #632 (got 11 columns instead of 16)
    Line #633 (got 11 columns instead of 16)
    Line #634 (got 11 columns instead of 16)
    Line #635 (got 11 columns instead of 16)
    Line #636 (got 11 columns instead of 16)
    Line #637 (got 11 columns instead of 16)
    Line #638 (got 11 columns instead of 16)
    Line #639 (got 11 columns instead of 16)
    Line #640 (got 11 columns instead of 16)
    Line #641 (got 11 columns instead of 16)
    Line #642 (got 11 columns instead of 16)
    Line #643 (got 12 columns instead of 16)
    Line #644 (got 12 columns instead of 16)
    Line #645 (got 11 columns instead of 16)
    Line #646 (got 11 columns instead of 16)
    Line #647 (got 11 columns instead of 16)
    Line #648 (got 12 columns instead of 16)
    Line #649 (got 12 columns instead of 16)
    Line #650 (got 12 columns instead of 16)
    Line #651 (got 11 columns instead of 16)
    Line #652 (got 12 columns instead of 16)
    Line #653 (got 12 columns instead of 16)
    Line #654 (got 12 columns instead of 16)
    Line #655 (got 12 columns instead of 16)
    Line #656 (got 12 columns instead of 16)
    Line #657 (got 11 columns instead of 16)
    Line #658 (got 12 columns instead of 16)
    Line #659 (got 12 columns instead of 16)
    Line #660 (got 12 columns instead of 16)
    Line #661 (got 12 columns instead of 16)
    Line #662 (got 11 columns instead of 16)
    Line #663 (got 11 columns instead of 16)
    Line #664 (got 11 columns instead of 16)
    Line #665 (got 11 columns instead of 16)
    Line #666 (got 11 columns instead of 16)
    Line #667 (got 11 columns instead of 16)
    Line #668 (got 11 columns instead of 16)
    Line #669 (got 11 columns instead of 16)
    Line #670 (got 12 columns instead of 16)
    Line #671 (got 12 columns instead of 16)
    Line #672 (got 12 columns instead of 16)
    Line #673 (got 11 columns instead of 16)
    Line #674 (got 11 columns instead of 16)
    Line #675 (got 11 columns instead of 16)
    Line #676 (got 11 columns instead of 16)
    Line #677 (got 11 columns instead of 16)
    Line #678 (got 11 columns instead of 16)
    Line #679 (got 11 columns instead of 16)
    Line #680 (got 11 columns instead of 16)
    Line #681 (got 12 columns instead of 16)
    Line #682 (got 11 columns instead of 16)
    Line #683 (got 11 columns instead of 16)
    Line #684 (got 11 columns instead of 16)
    Line #685 (got 12 columns instead of 16)
    Line #686 (got 12 columns instead of 16)
    Line #687 (got 12 columns instead of 16)
    Line #688 (got 12 columns instead of 16)
    Line #689 (got 11 columns instead of 16)
    Line #690 (got 12 columns instead of 16)
    Line #691 (got 12 columns instead of 16)
    Line #692 (got 12 columns instead of 16)
    Line #693 (got 12 columns instead of 16)
    Line #694 (got 11 columns instead of 16)
    Line #695 (got 12 columns instead of 16)
    Line #696 (got 12 columns instead of 16)
    Line #697 (got 12 columns instead of 16)
    Line #698 (got 12 columns instead of 16)
    Line #699 (got 12 columns instead of 16)
    Line #700 (got 12 columns instead of 16)
    Line #701 (got 12 columns instead of 16)
    Line #702 (got 12 columns instead of 16)
    Line #703 (got 12 columns instead of 16)
    Line #704 (got 12 columns instead of 16)
    Line #705 (got 12 columns instead of 16)
    Line #706 (got 13 columns instead of 16)
    Line #707 (got 13 columns instead of 16)
    Line #708 (got 12 columns instead of 16)
    Line #709 (got 12 columns instead of 16)
    Line #710 (got 13 columns instead of 16)
    Line #711 (got 13 columns instead of 16)
    Line #712 (got 12 columns instead of 16)
    Line #713 (got 13 columns instead of 16)
    Line #714 (got 13 columns instead of 16)
    Line #715 (got 13 columns instead of 16)
    Line #716 (got 13 columns instead of 16)
    Line #717 (got 13 columns instead of 16)
    Line #718 (got 13 columns instead of 16)
    Line #719 (got 12 columns instead of 16)
    Line #720 (got 11 columns instead of 16)
    Line #721 (got 11 columns instead of 16)
    Line #722 (got 12 columns instead of 16)
    Line #723 (got 11 columns instead of 16)
    Line #724 (got 11 columns instead of 16)
    Line #725 (got 12 columns instead of 16)
    Line #726 (got 11 columns instead of 16)
    Line #727 (got 11 columns instead of 16)
    Line #728 (got 12 columns instead of 16)
    Line #729 (got 11 columns instead of 16)
    Line #730 (got 12 columns instead of 16)
    Line #731 (got 12 columns instead of 16)
    Line #732 (got 12 columns instead of 16)
    Line #733 (got 12 columns instead of 16)
    Line #734 (got 11 columns instead of 16)
    Line #735 (got 11 columns instead of 16)
    Line #736 (got 12 columns instead of 16)
    Line #737 (got 12 columns instead of 16)
    Line #738 (got 12 columns instead of 16)
    Line #739 (got 11 columns instead of 16)
    Line #740 (got 11 columns instead of 16)
    Line #741 (got 11 columns instead of 16)
    Line #742 (got 11 columns instead of 16)
    Line #743 (got 11 columns instead of 16)
    Line #744 (got 11 columns instead of 16)
    Line #745 (got 12 columns instead of 16)
    Line #746 (got 11 columns instead of 16)
    Line #747 (got 11 columns instead of 16)
    Line #748 (got 11 columns instead of 16)
    Line #749 (got 11 columns instead of 16)
    Line #750 (got 12 columns instead of 16)
    Line #751 (got 12 columns instead of 16)
    Line #752 (got 13 columns instead of 16)
    Line #753 (got 13 columns instead of 16)
    Line #754 (got 11 columns instead of 16)
    Line #755 (got 11 columns instead of 16)
    Line #756 (got 11 columns instead of 16)
    Line #757 (got 11 columns instead of 16)
    Line #758 (got 12 columns instead of 16)
    Line #759 (got 12 columns instead of 16)
    Line #760 (got 12 columns instead of 16)
    Line #761 (got 12 columns instead of 16)
    Line #762 (got 12 columns instead of 16)
    Line #763 (got 12 columns instead of 16)
    Line #764 (got 11 columns instead of 16)
    Line #765 (got 11 columns instead of 16)
    Line #766 (got 12 columns instead of 16)
    Line #767 (got 12 columns instead of 16)
    Line #768 (got 12 columns instead of 16)
    Line #769 (got 12 columns instead of 16)
    Line #770 (got 12 columns instead of 16)
    Line #771 (got 12 columns instead of 16)
    Line #772 (got 11 columns instead of 16)
    Line #773 (got 12 columns instead of 16)
    Line #774 (got 12 columns instead of 16)
    Line #775 (got 12 columns instead of 16)
    Line #776 (got 11 columns instead of 16)
    Line #777 (got 11 columns instead of 16)
    Line #778 (got 11 columns instead of 16)
    Line #779 (got 12 columns instead of 16)
    Line #780 (got 12 columns instead of 16)
    Line #781 (got 12 columns instead of 16)
    Line #782 (got 13 columns instead of 16)
    Line #783 (got 13 columns instead of 16)
    Line #784 (got 13 columns instead of 16)
    Line #785 (got 13 columns instead of 16)
    Line #786 (got 13 columns instead of 16)
    Line #787 (got 13 columns instead of 16)
    Line #788 (got 13 columns instead of 16)
    Line #789 (got 13 columns instead of 16)
    Line #790 (got 11 columns instead of 16)
    Line #791 (got 11 columns instead of 16)
    Line #792 (got 12 columns instead of 16)
    Line #793 (got 12 columns instead of 16)
    Line #794 (got 11 columns instead of 16)
    Line #795 (got 12 columns instead of 16)
    Line #796 (got 13 columns instead of 16)
    Line #797 (got 12 columns instead of 16)
    Line #798 (got 13 columns instead of 16)
    Line #799 (got 13 columns instead of 16)
    Line #800 (got 13 columns instead of 16)
    Line #801 (got 12 columns instead of 16)

# advanced indexing