In [35]:
import numpy as np

In [36]:
a=np.array([1,2,3], dtype='int8')
print(a)

[1 2 3]


In [37]:
b=np.array([[9.0,6.0,3.0],[5.0,7.0,4.0]])
print(b)

[[9. 6. 3.]
 [5. 7. 4.]]


In [38]:
# get dimensions
a.ndim

1

In [39]:
b.ndim

2

In [40]:
a.shape

(3,)

In [41]:
b.shape

(2, 3)

In [42]:
a.dtype

dtype('int8')

In [43]:
a.itemsize

1

In [44]:
a.nbytes

3

# accessing/changing specific elements,row,columns

In [45]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [46]:
#get a specific element
a[0,5]

6

In [47]:
a[0,-3]

5

In [48]:
#get row only
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [49]:
#get column only
a[:,3]

array([ 4, 11])

In [50]:
#[startindex:endindex:stepsize]
a[0,2:-1:1]

array([3, 4, 5, 6])

In [51]:
#3d array
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [52]:
a[1,0,1]

6

In [53]:
a[:,1,:]

array([[3, 4],
       [7, 8]])

# initilizing different types of arrays

## all zeros
np.zeros(2,2)

In [56]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [57]:
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [60]:
np.full((2,2),99, dtype=float)

array([[99., 99.],
       [99., 99.]])

In [65]:
np.full_like(a,4)

array([[[4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4]]])

In [66]:
np.random.rand(4,2)

array([[0.31229693, 0.06882753],
       [0.11038974, 0.16200064],
       [0.75577967, 0.89831417],
       [0.78350509, 0.71525743]])

In [68]:
np.random.random_sample(a.shape)

array([[[0.47009442, 0.18087331],
        [0.00967316, 0.82803441]],

       [[0.36875894, 0.5677564 ],
        [0.13064586, 0.86050571]]])

In [71]:
np.random.randint(10,50, size=(3,3))

array([[16, 10, 30],
       [40, 12, 16],
       [44, 14, 46]])

In [72]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
output =np.ones((5,5))
print(output)
z= np.zeros((3,3))
z[1,1]=9
print(z)
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [89]:
a=np.array([1,2,3])
b=a.copy()
a[0]=100
b[0]=200
print(a)
print(b)

[100   2   3]
[200   2   3]


# mathematics with numpy

In [91]:
a=np.array([1,2,3])


In [92]:
a+2

array([3, 4, 5])

In [93]:
a-2

array([-1,  0,  1])

In [94]:
a*2

array([2, 4, 6])

In [95]:
a/2

array([0, 1, 1])

In [96]:
a**2

array([1, 4, 9])

In [97]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# statistics

In [100]:
a=np.array([[4,3,5],[7,6,4]])

In [103]:
np.min(a,axis=0)

array([4, 3, 4])

In [105]:
np.max(a,axis=0)

array([7, 6, 5])

In [106]:
np.sum(a)

29

In [107]:
np.sum(a,axis=0)

array([11,  9,  9])

In [108]:
np.sum(a,axis=1)

array([12, 17])

# Reorganizing Arrays

In [110]:
before=np.array([[4,3,5,9],[7,6,4,8]])
before

array([[4, 3, 5, 9],
       [7, 6, 4, 8]])

In [113]:
after=before.reshape((4,2))
after

array([[4, 3],
       [5, 9],
       [7, 6],
       [4, 8]])

In [114]:
# vertically stacking vectors
v1=np.array([4,3,5,9])
v2=np.array([7,6,4,8])
np.vstack([v1,v2])


array([[4, 3, 5, 9],
       [7, 6, 4, 8]])

In [115]:
np.hstack([v1,v2])

array([4, 3, 5, 9, 7, 6, 4, 8])